name = "vertz-landing"
compatibility_date = "2025-01-01"
workers_dev = true

[assets]
directory = "./"
not_found_handling = "single-page-application"

[[routes]]
pattern = "vertz.dev"
custom_domain = true
