[test]
coveragePathIgnorePatterns = [
  "**/codegen/dist/**",
  "**/compiler/dist/**",
  "**/create-vertz-app/dist/**",
  "**/db/dist/**",
  "**/errors/dist/**",
  "**/schema/dist/**",
  "**/tui/dist/**",
  "**/ui/dist/**",
  "**/server/dist/**",
]
